// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  box_section: dynamic(() => import("./BoxSection")),
  carousel: dynamic(() => import("./Carousel")),
  hero_banner: dynamic(() => import("./HeroBanner")),
  mobile_app_section: dynamic(() => import("./MobileAppSection")),
  product_list: dynamic(() => import("./ProductList")),
  sales_pitch_section: dynamic(() => import("./SalesPitchSection")),
  tile_section: dynamic(() => import("./TileSection")),
  why_array: dynamic(() => import("./WhyArray")),
};
